import { Fragment, ReactNode } from 'react';

export default function Head(): ReactNode {
  return (
    <Fragment>
      <title>OpenTable - Restaurant</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Fragment>
  );
}
